### ISSUE TITLE
Version in core release zip is 1.0

### ISSUE THREAD

**Issue by davewongillies** [rolandking/openFPGA-Athena#1]
Noticed that the version of the core in [`core.json`](https://github.com/rolandking/openFPGA-Athena/blob/master/dist/Cores/_CORE_/core.json#L10) is still `1.0` which means that the latest versions won't show up on [openfpga-cores-inventory](https://openfpga-cores-inventory.github.io/analogue-pocket/) which is used by the various updaters.

**Comment by rolandking** [comment]
oh I didn’t know anything read that version. Let me go do ANOTHER version

**Comment by davewongillies** [comment]
Thanks, I just successfully pulled down the latest release using pupdate
